import React from 'react'
import { Link } from 'react-router-dom'
import Carousel from './utils/Carousel'


const Home = () => {
    const viewCollections = [
        {
            id: 1,
            imgLocation: "/images/Car View/View 1.jpg",
            alt: "View 1"
        },
        {
            id: 2,
            imgLocation: "/images/Car View/View 2.jpg",
            alt: "View 2"
        },
        {
            id: 3,
            imgLocation: "/images/Car View/View 3.jpg",
            alt: "View 3"
        },
        {
            id: 4,
            imgLocation: "/images/Car View/View 4.jpg",
            alt: "View 4"
        },
        {
            id: 5,
            imgLocation: "/images/Car View/View 5.jpg",
            alt: "View 5"
        },
        {
            id: 6,
            imgLocation: "/images/Car View/View 6.jpg",
            alt: "View 6"
        },
        {
            id: 7,
            imgLocation: "/images/Car View/View 7.jpg",
            alt: "View 7"
        },
        {
            id: 8,
            imgLocation: "/images/Car View/View 8.jpg",
            alt: "View 8"
        },
        {
            id: 9,
            imgLocation: "/images/Car View/View 9.jpg",
            alt: "View 9"
        },
        {
            id: 10,
            imgLocation: "/images/Car View/View 10.jpg",
            alt: "View 10"
        },
    ];
  return (
    <div className="container">
        <h1 className="quicksand-bold title">INTRODUCING 2023 BUGATTI W16 MISTRAL</h1>
        <section className="car-descriptions">
            <Carousel collections={viewCollections} />
            <section className="quicksand-regular description">
                <p>Bugatti's W-16 will soon come to an end. The only one of its type, this 8-liter quad-turbo unit has powered all 21st-century Bugattis, from the original Veyron to the Chiron Super Sport 300+, where it generates a brutal 1578 hp. Not even Bugatti is immune to emissions regulations and the need to electrify, so the remarkable W-16 is going away, but not without a proper celebration. This is the Mistral, an open-top roadster derived from the Chiron, that provides the final home for the W-16.</p>
                <p>The Mistral uses a new carbon-fiber monocoque based on the Chiron's, yet the company points out that it's not just a Chiron tub with a big hole cut out where the roof would be. This new chassis allowed Bugatti designers to give the Mistral a very distinct look from the Chiron. Its engine is shared with the Super Sport 300+, and—as with all 16-cylinder Bugattis—it powers all four wheels via a dual-clutch transaxle.</p>
                <p>The engine breathes through two intakes just above the headrests. Those intakes double as rollover protection, carbon-fiber pieces able to support the weight of the car. Out back, the X-shaped taillight motif first shown on the Bolide is adapted here, giving the Mistral a distinct look while providing a lot of ventilation for the immense heat generated by the powertrain.</p>
                <p>Inside, the interior is very much Chiron, though with some new details including quilted leather on the door panels, and a recreation of Rembrandt Bugatti's famous elephant sculpture within the shifter. Naturally, customization will be virtually limitless.</p>
                <p>The Bugatti W16 Mistral's dimensions weren't mentioned by the automaker when the car was unveiled, but its length, width, and height are likely to be similar to the Chiron. That car is 80.2 inches wide, 178.9 inches long, and only 47.7 inches tall.</p>
                <p>Bugatti plans to build 99 examples of the Mistral, with a price of €5 million (around $5.1 million at the time of writing). Naturally, all are sold out, and when production ends, so too will the 16-cylinder automotive engine. What a send-off.</p>
            </section>
        </section>
        <section className="features">
            <main className="engine-link">
            <Link to="/engine">
                <img src="/images/08 BUGATTI_W16.jpg" alt="engine image" />
            </Link>
            <h4 className="quicksand-semibold">Engine</h4>
            </main>
            <main className="interior-link">
            <Link to="/interior">
                <img src="/images/Bugatti-Interior-Image-Icon.jpg" alt="interior image" />
            </Link>
            <h4 className="quicksand-semibold">Interior</h4>
            </main>
        </section>
        <Link className='quicksand-semibold contact-link' to="/contact">Contact Us</Link>
    </div>
  )
}

export default Home